name: Compilar LaTeX (Documentacion)

# El workflow se dispara con pushes o pull requests
on:
  push:
    branches:
      - main
      - documentation
    paths:
      - 'documentation/**' # Solo se ejecuta si hay cambios en esta carpeta
  pull_request:
    branches:
      - main
    paths:
      - 'documentation/**'

jobs:
  build_latex:
    runs-on: ubuntu-latest
    
    steps:
      # 1. Clona tu repositorio en la máquina virtual
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      # 2. Compila el archivo LaTeX
      - name: Compilar documento LaTeX
        uses: xu-cheng/latex-action@v3
        with:
          working_directory: documentation
          root_file: main.tex 

      # 3. Guarda el PDF generado como un artefacto descargable
      - name: Subir PDF generado
        uses: actions/upload-artifact@v4
        with:
          name: Documentacion-PDF
          path: documentation/main.pdf